[package]
name = "unishare"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "1.2", features = ["api-all"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
