name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release
 